name: AwesomeCI-Demo-Java

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    container:
      image: openjdk:11.0.3-jdk-stretch
    
    services:
      postgres:
        image: postgres:12-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: circle_test
        ports:
        - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: ./gradlew build -x test
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      with:
        sudo: false
    - name: Build with Gradle
      run: ./gradlew test --stacktrace
    - name: Generate code coverage report
      run: ./gradlew jacocoTestReport
    - name: Assemble JAR
      run: ./gradlew assemble
